#pragma once
#include "ElectricLocomotive.h"
#include "MotorLocomotive.h"
#include "SteamLocomotive.h"
#include "DiningCar.h"
#include "SleepingCar.h"
#include "Closed.h"
#include "Open.h"
#include "Cistern.h"